agent_config:
  # OPTIONS: "DQN", "DDPG", "TD3", "SAC", "CrossQ"
  active_algorithm: "SAC"  
  learning_rate: 0.0003
  discount_factor_gamma: 0.99
  experience_replay_size: 100000
  batch_size: 64

environment_config:
  lidar_scan_beams: 24
  maximum_steps_per_episode: 500
